apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  default.conf: |-
    server {
      listen 8080;
      location /api/v1/movies {
        proxy_pass http://movie-service:8001/api/v1/movies;
     }
     location /api/v1/casts {
       proxy_pass http://cast-service:8002/api/v1/casts;
     }
    }


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.nginx.hpa.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.nginx.image.repository }}
          ports:
            - containerPort: {{ .Values.nginx.image.port }}
          volumeMounts:
            - name: {{ .Chart.Name }}-config
              mountPath: /etc/nginx/conf.d
      volumes:
        - configMap:
            name: {{ .Chart.Name }}-config
          name: {{ .Chart.Name }}-config

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: {{ .Chart.Name }}-hpa
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: {{ .Chart.Name }}-deployment
 minReplicas: {{ .Values.nginx.hpa.minReplicas }}
 maxReplicas: {{ .Values.nginx.hpa.maxReplicas }}
 targetCPUUtilizationPercentage: {{ .Values.nginx.hpa.targetCPUUtilizationPercentage }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
spec:
  selector:
    app: {{ .Chart.Name }}
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    nodePort: {{ .Values.nginx.nodeport.nodeport }}
    port: {{ .Values.nginx.nodeport.port }}
    targetPort: {{ .Values.nginx.image.port }}
